# Generated by Django 5.0.6 on 2024-07-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description provided')),
                ('video_file', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='CommercialVideo',
        ),
    ]
