# Generated by Django 5.0.6 on 2024-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_booking_delete_appointment_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='events/')),
                ('description', models.TextField()),
            ],
        ),
    ]
